device: '0'
model: 'mnist'

input_x: 28
input_y: 28
input_c: 1
num_class: 10

batch_size: 512
epochs: 20
val_split: 0.1
loss: "categorical_crossentropy"
optimizer: "adam"
metrics: 
  - "accuracy"

pt_name: 'mnist_model.pt'